### ISSUE TITLE
create entry_point for executables to resample an image from command line

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#165]
The iDVC app to work from remote requires to resample data on the remote machine. This should be done by command line with the execution of a script or an entry_point.

```yaml

build:
  entry_points:
    - resample = ccpi.viewer.cli.resample:main
    - crop = ccpi.viewer.cli.crop:main
 ```

The executable should accept:
* input filename
* output filename (optional as it could be generated from the input filename)
* target size in kB
* output format

```
resample --input input_file.npy --output output_file.mha --size 1000
crop --input input_file.npy --output output_file.mha --extent 100:200:320:421:402:506
```

**Comment by lauramurgatroyd** [comment]
There may be cases where we want to crop and resample at the same time. We don't have the methods to do this at the moment in a single reader (except in hdf5) but it's something we should do later

**Comment by lauramurgatroyd** [comment]
In the case of a raw file we also need to be given:

- dimensions
- is it fortran
- is it big endian
- type code

In case of a hdf5 file:

- dataset name

For all file types I think they should also set whether its acquisiton data - in this case we don't resample in z direction

**Comment by paskino** [comment]
I guess we could use `docopt` to parse input parameters. Or better `yaml` as it comes with python, so we don't add any dependency?

> For all file types I think they should also set whether its acquisiton data - in this case we don't resample in z direction

This may be a good idea, but I'd code it generically allowing the user to specify `resample_z: true/false`

So in the end the yaml file could be

```yaml
array:
  shape: (1024,1024,1024)
  is_fortran: false
  is_bigendian: true
  typecode: 'float32'
  group_name: /tomosomething # valid for HDF5 and Zarr
resample:
  target_size: 1e7
  resample_z: true
output:
  filename: "this_fname.nxs"
  format: hdf5 # npy, METAImage, NIFTI (or Zarr to come)
```
